### ISSUE TITLE
would it be possible to improve the parsing of the parameter files ? 

### ISSUE THREAD

**Issue by 12rambau** [ec-jrc/GWB#1]
In the current implementation, the parameters files leave few to no flexibility to the end user. It has also changed from version 1.8.5 to 1.8.6 meaning that every batch process using GWB need to be upgraded on regular basis to meet the new file format. 

Let's take the `GWB_DIST` as an example:
This is the default parameter file. The user is supposed to copy it and change the 2 values in the `*` lines: 

> the blank line at the end is mandatory

```
 ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; GWB_DIST parameter file:
;; NOTE: do NOT delete or add any lines in this parameter file!
;;
;; DIST: Euclidean Distance + Hypsometric Curve
;; Input image requirements: 1b-background, 2b-foreground, optional: 0b-missing
;;
;; Please specify entries at lines 17-18 ONLY using the following options:
;;
;; line 17: Foreground connectivity: 8 (default) or 4 
;; line 18: 1-Eucl.Distance only   or  2- Eucl.Distance + Hysometric Curve
;;
;; an example parameter file with default settings would look like this:
;; 8
;; 1
****************************************************************************
8
1
****************************************************************************

```

prior to 1.8.5, this was also working: 
```
















8
1


```

after 1.8.6 you need to keep the `*` lines : 
```















****************************************************************************
8
1
****************************************************************************

```

Don't you think it would make sense to simply parse this file and remove `;;` comments lines ? If so a file like: 
```
8
1
```

or 

```
;; I'm the very long explainantion about why I decided to use 8 connectivity parameter 
;; instead of the 4 one 
;; that wasn't so easy to decide
;; ********************
8
1
;; *********************
```

**Comment by vogtpet** [comment]
all modules are set to read the exact module-specific line numbers between and including the ;; **** lines. This recent change, now including the two surrounding  ;;**** lines, was needed to prevent the user from manipulating the input parameter file format. The easiest way for me to test for correct input parameters is to do it this way. For example, for the module GWB_DIST, it will read line 16-19 of the respective input parameter file and that section must start and end with ;;****
Giving users the liberty to change things as they wish very much increases the complexity of my code to verify their input. I don't see any problem for the user in using the provided module template and just amending the values enclosed between the  final ;; **** lines.

**Comment by 12rambau** [comment]
For batch processing that's a real issue. because you need to know exactly at which line you need to start writing the parameters and that's always changing.

On the technical side that would be (according to me) super easy:
-> read each line and create a list 
-> remove every line that starts with ";;"
-> trim "/n"
-> count the number of remaining lines (that's the actual parameter) and run the same parameter check as before 

If you don't have the time to work on it I would be happy to have a look and see if a PR is possible. Could you point me to where it's done in the DIST function as a starting point ?

**Comment by vogtpet** [comment]
I don't understand where the issue is here: batch-processing reads the parameter file once, extracts the settings, and then applies them to all tif images. Reading the parameter file is done by the respective module. Please also note that GWB is not strictly designed for SEPAL but can be used on any Linux system. Unless you have a really striking argument I do not really want to change the current setup.
To see the startup test sequence, for example in  /opt/GWB/tools/source/GWB_DIST.pro, all up to line 260 are validation checks on the images to be processed and line 110-130 on the input file itself.
I don't see the point why the input parameter file should be allowed to have all kind of formatting. Plus if you give the user the choice to modify, all kind of issues can happen that are out of your control.

**Comment by 12rambau** [comment]
I was thinking about batch processing on parameters where I need to write down the parameter file as many time as I want to run the analysis.

I clearly understand that GWB is not entirely designed for SEPAL but all the other parameter file that I know (.ini, .yaml, setup.py, .toml, requirements.txt, and the exotic one from the libs I was using during my phd) supports comments. 

In general it allows 2 things: 
- automatically generate these parameter files in another workflow by keeping only the values/variables needed (the SEPAL implementation is an example) 
- use comments to explain stuff before sharing the parameter file with someone else

Regarding the code, I'll write it in a language I know for the DIST use case: 
```python
# init the parameter list 
params= []

# read the file line by line to extract parameters 
with open(mod_params) as fp:
    while line:
        line = line.strip()
        if line.startswith(";;") or line == "":
            continue
        else:
            params.append(line)

# do the param number check 
if len(params) != 2:
    raise Exception(f"the number of parameters should be 2, {len(params)} given. check the format of your paramter file")

# init the variables and continue with the already existing var checks
c_FGconn = params[0]
addhmc = params[1]
```

12 lines of code for making all the previously shown parameter files valid. Nothing fancy I'm sure it can be transformed in IDL

**Comment by vogtpet** [comment]
Pierrick, I can implement your pseudo-code section in the IDL modules. It will have the advantage that the user, or I, can add additional notes, before the actual parameter section, without breaking reading the parameter file. I will look into this in the next days and then send you an example for testing, ok?

**Comment by 12rambau** [comment]
that would be great !

**Comment by vogtpet** [comment]
here is a quick test for the DIST module: download [GWB_DIST.sav](https://ies-ows.jrc.ec.europa.eu/gtb/GWB/tmp/GWB_DIST.sav), place it in /opt/GWB/tools/
and then run as usual. This version is compatible with the existing dist-parameters.txt but also happy if that file has at least two _consecutive_ lines with the two input parameters in the correct format,  and all lines starting with ';' or '*' will be skipped. Please let me know if this is what you need. Thanks!

**Comment by 12rambau** [comment]
From my original request:
- file containing only value ✔️ 
- file containing mix of comments ";;" and "***" ✔️ 
- file containing the extra lines ✔️ 
- file containing empty lines ❌ 

This is the only one that didn't pass the tests : 
```



8
1
```

According to what you wrote that's normal and fine by me. That's perfect !

**Comment by vogtpet** [comment]
good, now please redownload and test the same again with an updated sav-file that should now also work on input files having empty lines. The only condition now is that the parameter lines must be subsequent, in the correct order as outlined in the template file, and the values must start at the first position of the line, here like this:
```
8
1
```

and not like this (wrong sequence):
```
1
8
```
or like that (input lines not subsequent):
```

    8



 1
```


if that is ok for you, then I can add this to all other modules for the next release, please let me know.

**Comment by 12rambau** [comment]
revision on my previous message then : 
- file containing only value ✔️
- file containing mix of comments ";;" and "***" ✔️
- file containing the extra lines ✔️
- file containing empty lines ✔️ 
- file containing mix of everything ✔️ 

it covers all the situations I could think about and prevent the classic loophole: 
- wrong order
- split parameters 
- inline comments

the error message is the following for all these cases: 
```
Foreground connectivity is not 8 or 4.
```

meaning that the parsing went wrong. 

I like it a lot, that seems perfect for me

**Comment by vogtpet** [comment]
ok, thanks for the testing and feedback. I will add this into the other modules then, and together with a revised GWB_REC make  a new version 1.8.8 sometime within the next week or two
