### ISSUE TITLE
add an edge parameter to SPA ? 

### ISSUE THREAD

**Issue by 12rambau** [ec-jrc/GWB#2]
Around me, colleagues are always using `GWB_MSPA` even though they just need the `GWB_SPA` classes. The only parameter missing in `GWB_SPA` that they really need to use is the edge width. 

Would it be possible to add this parameter to the SPA command or is it part of the reason it's way faster than MSPA ?

**Comment by vogtpet** [comment]
Page 9 of the [MSPA_Guide](https://ies-ows.jrc.ec.europa.eu/gtb/GTB/MSPA_Guide.pdf): SPA is restricted to edge width = 1 and 8-connectivity.
