### ISSUE TITLE
Is GWB running in parallel ? 

### ISSUE THREAD

**Issue by 12rambau** [ec-jrc/GWB#4]
My guess is no but I prefer to ask the question. I have to opportunity to use big AWS machines with lots of CPU but I'm not sure it's making sense. 

So the question is in the title: Is GWB running in parralel?

**Comment by vogtpet** [comment]
Each GWB module is coded to use as many CPUs as possible, if that is possible.
In addition, you can run each GWB module in parallel as long as each run uses its own output directory. This setup was necessary anyway to allow multiple users running GWB at the same time
