### ISSUE TITLE
mspa_lin64

### ISSUE THREAD

**Issue by zushika** [ec-jrc/GWB#7]
I tried to run the GWB_MSPA on ILD 8.9 (Windows 11) but faced an error message "% FILE_COPY: Unable to expand wildcards in file path, or file does not exist: E:\GWB-main\GWB-main\tools/mspa_lin64". It seems mspa_line64 file is missing in the tools directory. Can you upoload the file?

**Comment by vogtpet** [comment]
From the [readme](https://github.com/ec-jrc/GWB) "GWB is cmd-line application for **Linux 64bit** servers".  Meaning, GWB is not designed to work on MS-Windows and you also don't need IDL to run the application. Just install the entire [GWB package](https://forest.jrc.ec.europa.eu/en/activities/lpa/gwb/) for your Linux distribution. If you want to run MSPA on MS-Windows, install the desktop application [GTB](https://forest.jrc.ec.europa.eu/en/activities/lpa/gtb/) instead.
